Update the import of adafruit_dps310 to latest
This fixes this after the latest DPS310 release. I assumed we want the advanced by default on the Fun House.
```py
Traceback (most recent call last):
  File "code.py", line 13, in <module>
  File "adafruit_funhouse/__init__.py", line 110, in __init__
  File "adafruit_funhouse/peripherals.py", line 86, in __init__
AttributeError: 'module' object has no attribute 'DPS310'
```
https://github.com/adafruit/Adafruit_CircuitPython_DPS310/pull/15